### ISSUE TITLE
Remove Bootstrap dependency

### ISSUE THREAD

**Issue by boclifton-MSFT** [boclifton-MSFT/bookmark-searcher#1]
Currently using Bootstrap's minified CSS.  This adds a lot of size, so need to write CSS file only including the required styles.

**Comment by shikhar13012001** [comment]
I want to work on this issue, Can you please assign this to me?

**Comment by boclifton-MSFT** [comment]
Done!  Go get em, @shikhar13012001!

**Comment by shikhar13012001** [comment]
@boclifton-MSFT Thank you for assigning the issue, it was great, can you also add the hacktoberfest-accepted label to my PR and hacktoberfest topic to the repo, that would help me immensely.
Thanks again ! 🎊

**Comment by boclifton-MSFT** [comment]
@shikhar13012001 I think I did all that right.  Haven't messed with tags and labels much.  Let me know if you need anything else added!
